version: "3.9"
services:
  web:
    image: ghcr.io/wsdexe/postal:latest
    command: postal web-server
    network_mode: host
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped

  smtp:
    image: ghcr.io/wsdexe/postal:latest
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped

  worker:
    image: ghcr.io/wsdexe/postal:latest
    command: postal worker
    network_mode: host
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped

  runner:
    profiles: ["tools"]
    image: ghcr.io/wsdexe/postal:latest
    command: postal
    network_mode: host
    volumes:
      - /opt/postal/config:/config
